---

minio_server_datadirs: [ "/opt/minio-data-1", "/opt/minio-data-2" ]
minio_server_addr: ":9009"
minio_server_cluster_nodes: [ "http://sg-wa-a.ua.int/opt/minio-data-1", "http://sg-wa-a.ua.int/opt/minio-data-2", "http://sg-wa-b.ua.int/opt/minio-data-1", "http://sg-wa-b.ua.int/opt/minio-data-2" ]
minio_install_client: false
minio_access_key: "minio"
minio_secret_key: "minio131313"