---

minio_server_datadirs: [ "/opt/minio-data-1", "/opt/minio-data-2" ]
minio_server_addr: ":9009"
minio_server_cluster_nodes: [ "http://192.168.58.102/opt/minio-data-1", "http://192.168.58.102/opt/minio-data-2", "http://192.168.58.103/opt/minio-data-1", "http://192.168.58.103/opt/minio-data-2" ]
minio_install_client: false
minio_access_key: "minio"
minio_secret_key: "minio131313"
minio_server_release: "RELEASE.2020-04-10T03-34-42Z"
vault_minio_key: "{{ lookup('hashi_vault', 'secret=kv/data/wa/minio') }}"