---
bind_zone_dir: /var/local/named-zones
bind_zone_file_mode: '0660'
bind_allow_query:
  - any
bind_listen_ipv4:
  - any
bind_listen_ipv6:
  - none
bind_acls:
  - name: acl1
    match_list:
      - 192.168.0.0/16
bind_forwarders:
  - '8.8.8.8'
  - '8.8.4.4'
bind_dns_keys:
  - name: area.ua
    algorithm: hmac-md5
    secret: "azertyAZERTY123456"
bind_recursion: true
bind_query_log: 'data/query.log'
bind_check_names: 'master ignore'
bind_zone_master_server_ip: "192.168.58.102"
bind_zone_minimum_ttl: "2D"
bind_zone_ttl: "2W"
bind_zone_time_to_refresh: "2D"
bind_zone_time_to_retry: "2H"
bind_zone_time_to_expire: "2W"
bind_zone_domains:
  - name: 'area.ua'
    networks:
      - '192.168.58'
    name_servers:
      - vm1.area.ua.
      - vm3.area.ua.
    name_servers:
      - vm1
      - vm3
    hosts:
      - name: vm1
        ip: 192.168.58.101  
      - name: gitlab
        ip: 192.168.58.101    
      - name: vm2
        ip: 192.168.58.102
      - name: vm3
        ip: 192.168.58.103
      - name: minio
        ip: 192.168.58.103 
      - name: haproxy
        ip: 192.168.58.103  
      - name: vault
        ip: 192.168.58.103      
    hostmaster_email: admin